---
title: "metabolite"
author: "liyueer"
date: "2023-10-24"
output: html_document
---

load packages
```{r}
library(dplyr)
```


combine the taxonomy with experiment number
each taxonomy has at least 3 experiments
```{r}
strains <- read.csv("strains_in_mega.csv")
strains <- strains[!is.na(strains$taxid),]
strains <- strains[(strains$taxid != ""),]
nrow(strains)
strains$taxid <- as.numeric(strains$taxid)
strains[!grepl("^\\d+$", strains$taxid), ]
item<- strains

exp <- read.csv("exp_info.csv")
head(exp)
strains <- left_join(strains,exp,by = "taxonomy")
strains<-select(strains, c("taxonomy","taxid","exp_id","grouped_taxonomy"))
head(strains)
nrow(distinct(strains,taxonomy))
# 157
```

use the foldchange.dmrvf.fa data 
```{r}
count_fold_dmrvf <- read.csv("count_is.csv")
chemicals <- read.csv("chemicals.csv")
chemicals <- chemicals[,c("dname","Compound","inchikey")]

```

### count_fold_dmrvf select the maximum

```{r}
options(scipen = 999)  
options(digits = 7)   

# onlyn read 4 cols
count_fold_dmrvf <- select(count_fold_dmrvf, c("exp_id",chemicals$dname))

nrow(distinct(count_fold_dmrvf, exp_id))
nrow(distinct(strains, exp_id))
# strains[is.na(strains$exp_id), ]  10 rows
# result_left_join <- left_join(strains, count_fold_dmrvf, by = "exp_id")
# result_inner_join <- strains %>% inner_join(count_fold_dmrvf, by = "exp_id")
# difference_left <- anti_join(result_left_join, result_inner_join, by = "exp_id")


columns_to_max <- chemicals$dname
# "m_c18p_0046" "m_c18p_0112" "m_c18p_0038" "m_c18n_0283"

strains %>% left_join(count_fold_dmrvf, by = "exp_id") -> meta_strains

result <- meta_strains %>%
  group_by(taxonomy) %>%
  summarize(across(all_of(columns_to_max), ~if(all(is.na(.))) NA_real_ else max(., na.rm = TRUE)))

print(result)



missing<-strains %>%  anti_join(result, by = "taxonomy") # no unmatch result

item_short <- left_join(item, result,by="taxonomy") %>% .[,(ncol(.)-4):ncol(.)] # taxid and four compounds

compound_values <- chemicals[chemicals$dname %in% colnames(item_short)[2:5], "Compound"]
# compound_values <- paste(compound_values, "_AVG", sep = "")
colnames(item_short)[2:5] <- compound_values

item_short$taxid <- as.numeric(item_short$taxid)

```

Linear function normalization
```{r}
# Linear function normalization
nor_min_max=function(x){
  y=na.omit(x)
  return((x - min(y))/(max(y) - min(y)))
}

#  Min-Max normalization
item_short[, -1] <- lapply(item_short[, -1], nor_min_max)


```



```{r}
fold_dat <- reshape2::melt(item_short,na.rm = FALSE, measure.vars=c("PUTRESCINE","AGMATINE","ORNITHINE","CITRULLINE"),variable.name = "Metabolite",value.name = "foldchange_abundance")
# raw_dat$raw_abundance <- format(raw_dat$raw_abundance, scientific = FALSE)


fold_dat[fold_dat == "NaN"] <- NA


```

```{r}
raw_anno <- read.csv("iphylo_tree_items_for_anno.csv")
head(raw_anno)
head(fold_dat)

# final annotation data
anno_dat<- left_join(raw_anno, fold_dat, by="taxid")
# anno_2[is.nan(anno_2)] <- NA
head(anno_dat)

# label to show
anno_dat$Manual_label <- ifelse(anno_dat$foldchange_abundance > 0.095, anno_dat$id, NA)
anno_dat <- anno_dat %>%
  group_by(id) %>%
  mutate(Manual_label = ifelse(all(is.na(Manual_label)), NA, Manual_label[!is.na(Manual_label)][1]))

# final output tree_anno_leaf.csv
write.csv(anno_dat, "tree_anno_leaf_is.csv", row.names = F, na = "")

```





